### ISSUE TITLE
Tiles Pivot Are Bottom-Left

### ISSUE THREAD

**Issue by tileuser** [Seanba/SuperTiled2Unity#152]
In Tiled I have the Object Alignment as Center for the .tsx file, 
![0 1](https://user-images.githubusercontent.com/69766972/90341478-fb8f8c80-dfcd-11ea-9076-b2618283c32e.png)

but when I import the map into Unity, the tiles actually use the bottom-left pivot (0,0) instead of a center pivot (0.5, 0.5).
![0 2 (2)](https://user-images.githubusercontent.com/69766972/90341593-d5b6b780-dfce-11ea-893b-44fa1ab733a4.png)
![0 2 (3)](https://user-images.githubusercontent.com/69766972/90341591-d5b6b780-dfce-11ea-9acc-89f24f0a0da0.png)
(The blue tile is a game object with a sprite renderer attached. I went into the sprite editor and spliced the sprites to have a center pivot)

I'm not that experienced, and I may be completely wrong here,  but I think the problem comes from the [SuperTile ](https://github.com/Seanba/SuperTiled2Unity/blob/master/SuperTiled2Unity/Assets/SuperTiled2Unity/Scripts/SuperTile.cs)script. There is a public override void GetTileData() where it sets the tileData.sprite = m_Sprite; I used debug.log and found that m_Sprite.pivot is (0,0). Maybe this has to do with the problem, but I am not so sure.

In any case, I don't know why each tile's pivot is bottom-left nor how to change it to be center.

**Comment by Seanba** [comment]
Hi there, @tileuser. The object alignment is a relatively newer feature of Tiled and I simply haven't incorporated it yet into SuperTiled2Unity. I will try my best to find time to address this soon, within the next week, as I like to keep with Tiled.

**Comment by tileuser** [comment]
Oh ok. Thank you.

**Comment by Seanba** [comment]
Hi @tileuser. I just pushed up a new version of SuperTiled2Unity that supports all alignments for tile objects. Give it a try and let me know if you have any issues.

https://seanba.itch.io/supertiled2unity/devlog/172758/supertiled2unity-version-193

And thanks for making me aware of this problem.

**Comment by tileuser** [comment]
So the update did fix the tile alignment for Tiled Objects, but the other layers still have a bottom left pivot. 

![0 3 (2)](https://user-images.githubusercontent.com/69766972/91109239-65500c00-e648-11ea-852c-9c2734c419a9.png)
![0 3(3)](https://user-images.githubusercontent.com/69766972/91109241-65e8a280-e648-11ea-86eb-9f641c7919bc.png)

(When I play in Unity the collision works correctly, I can't go where the yellow tile is)


There is a similarity to how it looks in Tiled, which leads me to believe that this might be a problem within Tiled and not SuperTiled2Unity. I thought this was a visual glitch or something like that, but now I am not so sure.

![0 3(2)](https://user-images.githubusercontent.com/69766972/91109240-65e8a280-e648-11ea-8f9d-29dba4500e92.png)
(The tiles in the object layer are the yellow tiles. The red tiles are in the collision layer and is the position the yellow tiles should be covering.)

Thanks for fixing the previous problem though.

**Comment by Seanba** [comment]
Hi again, @tileuser. I'm re-opening the issue, at least temporarily.

If I understand you correctly you have the following layers in your TMX file:
1. Object Layer
2. Collision Layer
3. Ground Layer

Is it your Collision and Ground layers that seem off to you now? If so, then I think that is to be expected as these are Tile Layers. The `Object Alignment` property in the tileset is only used used as an anchor for the tiles when they are used as Tile Objects - not as tiles in a Tile Layer.

Tiles in a Tile Layer always use bottom-left as an anchor which I suspect is why Bjorn (the author of Tiled) made that the default alignment of Tile Objects as well.

**Comment by tileuser** [comment]
That makes sense. I thought the Object Alignment property would also make the tiles in the Tile Layer center. In retrospect, I should have realized the Object Alignment only worked with Tile Objects.  I am going to close the issue since the problem has been solved, but I have a final question. Is it possible to make the tiles in the Tile Layer centered, either through Unity or Tiled itself?

Thanks for the help.

**Comment by Seanba** [comment]
> Is it possible to make the tiles in the Tile Layer centered, either through Unity or Tiled itself?

You can probably accomplish something like with a custom importer but it will require you to write some code. You can learn about custom importers here: https://supertiled2unity.readthedocs.io/en/latest/manual/extending-the-importer.html

The tricky part would be keeping the collisions aligned with the tiles, though. Maybe it would be easier if you translated each tilemap by half of your tile dimensions?

For instance, if your tiles were 16x16 pixels then could translate your tilemaps like so to give the illusion that your tiles are in the center?

```
using SuperTiled2Unity.Editor;

[AutoCustomTmxImporter()]
 public class TileCenterTmxImporter : CustomTmxImporter
 {
     public override void TmxAssetImported(TmxAssetImportedArgs args)
     {
        var map = args.ImportedSuperMap;
        foreach (Tilemap tilemap in map.GetComponentsInChildren<Tilemap>())
        {
            float hx = 8 / args.AssetImporter.PixelsPerUnit;
            float hy = 8 / args.AssetImporter.PixelsPerUnit;
            tilemap.gameObject.transform.Translate(hx, -hy, 0);
        }
     }
 }
```
Warning that I'm just writing that code on the spot so it may not be exactly right. Make sure that is in a C# file that is in and `Editor` folder as it is an editor script.

**Comment by tileuser** [comment]
It works, just needed to modify it a little. 
I also added an offset for the tilemap layers to be at (0,0) because normally they are at (0,-1). I believe someone regarded this as an issue and you explained that it was a compromise in converting Tiled to Unity. Anyways, you have to raise the Y position by 1 because the tiles technically aren't there if you look at the tilemap cell bounds. This ends up making the tilemap layer positions to be (-0.5,-0.5) in the inspector.
```
using UnityEngine.Tilemaps;
using SuperTiled2Unity.Editor;

[AutoCustomTmxImporter()]
 public class TileCenterTmxImporter : CustomTmxImporter
 {
     public override void TmxAssetImported(TmxAssetImportedArgs args)
     {
        var map = args.ImportedSuperMap;
        foreach (Tilemap tilemap in map.GetComponentsInChildren<Tilemap>())
        {
            var tilemapTransform = tilemap.gameObject.transform;
            tilemapTransform.Translate(0, 1f, 0);

            float hx = 8 / args.AssetImporter.PixelsPerUnit;
            float hy = 8 / args.AssetImporter.PixelsPerUnit;
             tilemapTransform.Translate(hx - 1f, -hy, 0);
        }
     }
 }
```
Once again, thanks so much for helping me out.

**Comment by abondar** [comment]
@Seanba Hello!

Sorry for necroposting, but I thought that it is relevant to this issue, so may be you would be able to help me

I am new to unity and just figuring it out, so pardon me if I am missing some basic knowledge 

I discovered that when I call `tilemap.GetCellCenterWorld(position)` it gives me position of bottom-left corner of tile. 

After some investigation I ended up in this issue and, as far as I understood, it seems that changing tileset's `Object alignment` should change Tile Anchor accordingly. 

I've updated tileset's alignment to center
![image](https://github.com/user-attachments/assets/b040e877-717a-4a99-9a13-30fec863ad4c)

And tried reimporting it, but tile anchor has not changed 

I debugged tile's initialization, and it seems like `superTile.m_ObjectAlignment` is indeed loaded as `CENTER`, though `tilemap.GetCellCenterWorld(position)` still returns left bottom corner.

Is it intended behavior and I just misinterpreted your discussion above? 
Is there proper way to load tilemap with centered Tile Anchor?
