### ISSUE TITLE
Isometric tilelayer doesn't match imagelayer

### ISSUE THREAD

**Issue by starcid** [Seanba/SuperTiled2Unity#43]
I am doing some test by using SuperTiled2Unity, and I found in isometric mode, the image layers doesn't match the tile layer, their releative offset was wrong.
In Tiled map editor:
![image](https://user-images.githubusercontent.com/4112149/53392118-6c567980-39d3-11e9-899a-2902b7018963.png)
In Unity:
![image](https://user-images.githubusercontent.com/4112149/53392206-a9227080-39d3-11e9-9435-d1abdbfab8e6.png)
I have to adjust the tile layer position_x by adding an offset which is **SuperMap.m_Height * SuperMap.m_TileHeight** to match the image layer.
Object layer has the same problem with the tile layer.

**Comment by Seanba** [comment]
Hi there, @starcid. Do you mind sending me a Unity package of your project so I can test any fixes against it? I sometimes find that users are trying a combination of settings (orientation, offsets, infinite mode, pixels per unit, etc.) that I haven't accounted for. Thanks.

sean@seanba.com

**Comment by starcid** [comment]
Sure，
I have sent you a email(sean@seanba.com) which includes the unity package.
My unity version: 2018.3.6f1 Personal
SuperTiled2Unity Version:1.2.3
Thank you.

**Comment by Seanba** [comment]
Hi @starcid, this is fixed with version 1.2.4 of SuperTiled2Unity. Thanks.

**Comment by starcid** [comment]
Thanks, Seanba.
I reimport the resource with version 1.2.4 and I got the difference result with the 1.2.3 but still incorrect.
In unity(SuperTiled2Unity 1.2.4)
![image](https://user-images.githubusercontent.com/4112149/54113063-73917480-4422-11e9-9a06-067ce1d52a09.png)
You can see that the green tile's positions don't match the image layer's position.

**Comment by Seanba** [comment]
Hello again, @starcid. I just released version 1.2.5 that contains the real fix this. Last time around I only tested maps that were square (same number of tiles wide as high) and that lead me to believe, incorrectly, that I fixed the problem. Thanks for the bug report and sorry for the churn.

**Comment by starcid** [comment]
Yes, it works now.
Never mind and thank you for your great work.
